services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable"
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    ports:
      - "${SERVICE_PORT}:8123"
    restart: unless-stopped
    network_mode: host

volumes: 
  homeassistant_config: